#!/bin/sh

# Values
HOSTNAME=$(uname -n)
OS=$(lsb_release -sd | sed -e 's/"//g')
KERNEL=$(uname -sr)
UPTIME=$(uptime -p | sed -e 's/up //')
PACKAGES=$(pkgs) # fetchutils-git
SHELL=$(basename "$SHELL")
WM="hyprland"
TERMINAL=$(basename "$TERM")
EDITOR=$(basename "$EDITOR")

# Start
printf "\033[1;36m%s   \033[33m󰧱    \033[1;36m%s\033[0m\n" "${USER:-user}" "${HOSTNAME:-hostname}
\033[1;35mUPTIME:         \033[0m󰥔  ${UPTIME:-uptime}\033[0m
\033[1;35mOS:             \033[0m  ${OS:-os}\033[0m
\033[1;35mWM:             \033[0m ${WM:-wm}\033[0m
\033[1;35mKERNEL:         \033[0m  ${KERNEL:-kernel}\033[0m
\033[1;35mPACKAGES:       \033[0m  ${PACKAGES:-packages}\033[0m
\033[1;35mSHELL:          \033[0m󰈺  ${SHELL:-shell}\033[0m
\033[1;35mTERMINAL:       \033[0m  ${TERMINAL:-terminal}\033[0m
\033[1;35mEDITOR:         \033[0m  ${EDITOR:-editor}\033[0m"

exit 0
